{
    "config": {
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_auth": "Aktivieredie Authentifizierung in den Einstellungen von m\u00fctesync > Authentifizierung",
            "unknown": "Unerwarteter Fehler"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Host"
                }
            }
        }
    }
}